export const products = [
  {
    id: 1,
    name: "Stylish Red Shirt",
    company: "Roadster",
    price: 799,
    description: "High quality cotton shirt",
    stock: 25,
    stars: 4.2,
    reviews: 126,
    featured: true,
    image: [{ url: "https://picsum.photos/500/500?random=1" }],
  },
  {
    id: 2,
    name: "Wireless Earbuds",
    company: "Boat",
    price: 1399,
    description: "Noise cancelling, long battery",
    stock: 15,
    stars: 4.7,
    reviews: 98,
    featured: true,
    image: [{ url: "https://picsum.photos/500/500?random=2" }],
  },
  {
    id: 3,
    name: "Running Shoes",
    company: "Nike",
    price: 2499,
    description: "Comfortable sports shoes",
    stock: 18,
    stars: 4.5,
    reviews: 340,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=3" }],
  },
  {
    id: 4,
    name: "Smart Watch",
    company: "Noise",
    price: 1999,
    description: "Fitness tracking smart watch",
    stock: 30,
    stars: 4.1,
    reviews: 210,
    featured: true,
    image: [{ url: "https://picsum.photos/500/500?random=4" }],
  },
  {
    id: 5,
    name: "Denim Jeans",
    company: "Levis",
    price: 1899,
    description: "Slim fit denim jeans",
    stock: 20,
    stars: 4.3,
    reviews: 145,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=5" }],
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    company: "JBL",
    price: 2999,
    description: "Deep bass portable speaker",
    stock: 12,
    stars: 4.6,
    reviews: 189,
    featured: true,
    image: [{ url: "https://picsum.photos/500/500?random=6" }],
  },
  {
    id: 7,
    name: "Laptop Backpack",
    company: "American Tourister",
    price: 1599,
    description: "Water resistant backpack",
    stock: 22,
    stars: 4.4,
    reviews: 167,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=7" }],
  },
  {
    id: 8,
    name: "Gaming Mouse",
    company: "Logitech",
    price: 1299,
    description: "High precision gaming mouse",
    stock: 35,
    stars: 4.5,
    reviews: 312,
    featured: true,
    image: [{ url: "https://picsum.photos/500/500?random=8" }],
  },
  {
    id: 9,
    name: "Office Chair",
    company: "Green Soul",
    price: 6499,
    description: "Ergonomic office chair",
    stock: 10,
    stars: 4.2,
    reviews: 89,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=9" }],
  },
  {
    id: 10,
    name: "Casual Sneakers",
    company: "Puma",
    price: 2799,
    description: "Everyday casual sneakers",
    stock: 17,
    stars: 4.4,
    reviews: 201,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=10" }],
  },
  {
    id: 11,
    name: "Formal Shirt",
    company: "Arrow",
    price: 1699,
    description: "Perfect for office wear",
    stock: 28,
    stars: 4.1,
    reviews: 133,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=11" }],
  },
  {
    id: 12,
    name: "Headphones",
    company: "Sony",
    price: 3499,
    description: "Over-ear noise cancelling",
    stock: 14,
    stars: 4.6,
    reviews: 278,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=12" }],
  },
  {
    id: 13,
    name: "Mobile Charger",
    company: "Mi",
    price: 699,
    description: "Fast charging adapter",
    stock: 40,
    stars: 4.0,
    reviews: 490,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=13" }],
  },
  {
    id: 14,
    name: "LED Table Lamp",
    company: "Philips",
    price: 1199,
    description: "Eye care LED lamp",
    stock: 26,
    stars: 4.3,
    reviews: 156,
    featured: false,
    image: [{ url: "https://picsum.photos/500/500?random=14" }],
  },
];